spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/playlist
    username: summer
    password: hothot123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jwt:
    secret-key: SlNPTl9XRUJfVE9LRU5fVEVTVF9TRUNSRVRfS0VZUw==
    access-token-expiration: 180000 # 30분
    refresh-token-expiration: 1296000000 # 15일

  security:
    user:
      name: admin
      password: 1234
      roles: USER, ADMIN
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: http://localhost:8080/api/members/login/oauth2/code/google
        token-uri: https://oauth2.googleapis.com/token
        resource-uri: https://www.googleapis.com/oauth2/v2/userinfo




decorator:
  datasource:
    p6spy:
      enable-logging: true
---
spring:
  config:
    activate:
      on-profile: prod

decorator:
  datasource:
    p6spy:
      enable-logging: false
