server:
  shutdown: graceful

spring:
  profiles:
    default: local
    group:
      local:
        - oauth
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jwt:
    secret-key: SlNPTl9XRUJfVE9LRU5fVEVTVF9TRUNSRVRfS0VZUw==
    access-token-expiration: 180000 # 30분
    refresh-token-expiration: 1296000000 # 15일

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/playlist
    username: summer
    password: hothot123

  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: 0.0.0.0
      port: 6379

  security:
    user:
      name: admin
      password: 1234
      roles: USER, ADMIN

decorator:
  datasource:
    p6spy:
      enable-logging: true
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/playlist
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: 0.0.0.0
      port: 6379

decorator:
  datasource:
    p6spy:
      enable-logging: false

